accounts/urls.py
from django.urls import path
# viewsモジュールをインポート
from . import views
# viewsをインポートしてauth_viewという名前で利用する
from django.contrib.auth import views as auth_views

# URLパターンを逆引きできるように名前を付ける
app_name = 'accounts'

# URLパターンを登録するための変数
urlpatterns = [
    # サインアップページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して
    # viewsモジュールのSignUpViewをインスタンス化する
    path('signup/',
         views.SignUpView.as_view(),
         name = 'signup'),
    
    # サインアップ完了ページのビューの呼び出し
    # 「http(s)://<ホスト名>/signup_success/」へのアクセスに対して
    # viewsモジュールのSignUpSuccessViewをインスタンス化する
    path('signup_success/,',
         views.SignUpSuccessView.as_view(),
         name = 'signup_success'),
    
    # ログインページの表示
    # 「http(s)://<ホスト名>/signup/」へのアクセスに対して
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログインページを表示する
    path('login/',
         # ログイン用のテンプレート(フォーム)をレンダリング
         auth_views.LoginView.as_view(template_name = 'login.html'),
         name = 'login'
         ),
    
    # ログアウトを実行
    # 「http(s)://<ホスト名>/signout/」へのアクセスに対して
    # django.contrib.auth.views.LoginViewをインスタンス化して
    # ログアウトさせる
    path(
         'logout/',
         auth_views.LogoutView.as_view(template_name = 'logout.html'),
         name = 'logout'
         ),
]

photo/urls.py
from django.urls import path
from . import views

# URLパターンを逆引きできるように名前を付ける
app_name = 'photo'

# URLパターンを登録する
urlpatterns = [
    # photoアプリへのアクセスはviewsモジュールのIndexViewを実行
    path('', views.IndexView.as_view(), name = 'index'),
    
    # 写真投稿ページへのアクセスはviewsモジュールのCreatePhotoViewを実行
    path('post/', views.CreatePhotoView.as_view(), name = 'post'),
    
    # 登録完了ページへのアクセスはviewsモジュールのPostSuccessViewを実行
    path('post_done/',
        views.PostSuccessView.as_view(),
        name = 'post_done'
        ),
    
    # カテゴリ一覧ページ
    # photos/<categorystableのid値>にマッチング
    # <int:category>は辞書{category: id値(int)}としてCategoryViewに渡される
    path('photos/<int:category>',
        views.CategoryView.as_view(),
        name = 'photos_cat'
        ),
    
    # ユーザーの投稿一覧ページ
    # photos/<ユーザーテーブルのid値>にマッチング
    # <int:user>は辞書{user:id値(int)}としてCategoryViewに渡される
    path('user-list/<int:user>',
        views.UserView.as_view(),
        name = 'user_list'
        ),
    
    # 詳細ページ
    # photo-detail/<Photo postsテーブルのid値>にマッチング
    # <int:pk>は辞書{pk:id値(int)}としてDetailViewに渡される
    path('photo-detail/<int:pk>',
        views.DetailView.as_view(),
        name = 'photo_detail'
        ),
    
    # マイページ
    # mypage/へのアクセスはMypageViewをを実行
    path('mypage/', views.MypageView.as_view(), name = 'mypage'),
    
    # 投稿写真の削除
    # photo/<Photo postsテーブルのid値>/dekete/にマッチング
    # <int:pk>は辞書{pk:(int)}としてDetailViewに渡される
    path('photo/<int:pk>/delete/',
        views.PhotoDeleteView.as_view(),
        name = 'photo_delete'
       ),
]

photoproject/urls.py
from django.contrib import admin
from django.urls import path, include # include追加
# auth.viewsをインポートしてauth_viewsという名前で利用する
from django.contrib.auth import views as auth_views
# settingsを追加
from django.conf import settings
# staticを追加
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # photo.urlsへのURLパターン
    path('', include('photo.urls')),
    
    # accounts.urlsへのURLパターン
    path('', include('accounts.urls')),
    
    # パスワードリセットのためのURLパターン
    # PasswordResetConfirmViewがプロジェクトのurls.pyを参照するのでここに記載
    # パスワードリセット申し込みページ
    path('password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name = "password_reset.html"),
            name = 'password_reset'),
    
    # メール送信完了ページ
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name = "password_reset_sent.html"),
            name = 'password_reset_done'),
    
    # パスワードリセットページ
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
            template_name = "password_reset_form.html"),
            name = 'password_reset_confirm'),
    
    # パスワードリセット完了ページ
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name = "password_reset_done.html"),
            name = 'password_reset_complete'),
]

# urlpatternsにmediaフォルダーのURLパターンを追加
urlpatterns += static(
    # MEDIA_URL = 'media/
    settings.MEDIA_URL,
    # MEDIA_ROOTにリダイレクト
    document_root = settings.MEDIA_ROOT
    )

photo/models.py
from django.db import models
# accountsアプリのmodelsモジュールからCustomUserをインポート
from accounts.models import CustomUser

class Category(models.Model):
    '''投稿する写真のカテゴリを管理するモデル
    '''
    # カテゴリ名のフィールド
    title = models.CharField(
        verbose_name='カテゴリ',
        max_length=20)
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        
        Return(str):カテゴリ名
        '''
        return self.title
class PhotoPost(models.Model):
    '''投稿されたデータを管理するモデル
    '''
    # CustomUserモデル(のuser_id)とPhotoPostモデルを
    # 1対多の関係で結びつける
    # CumtomIserが親でPhotoPostが子の関係となる
    user = models.ForeignKey(
        CustomUser,
        # フィールドのタイトル
        verbose_name='ユーザー',
        # ユーザを削除する場合はそのユーザーの投稿データもすべて削除する
        on_delete=models.CASCADE
        )
    # Categoryモデル(のtitle)とPhotoPostモデルを
    # 1対多の関係で結びつける
    # Categoryが親でPhotoPostが子の関係となる
    category = models.ForeignKey(
        Category,
        # フィールドのタイトル
        verbose_name='カテゴリ',
        # カテゴリに関連つけられた投稿データが存在する場合は
        # そのカテゴリを削除できないようにする
        on_delete=models.PROTECT
        )
    # タイトル用のフィールド
    title = models.CharField(
        verbose_name='タイトル',
        max_length=200
        )
    # コメント用のフィールド
    comment = models.TextField(
        verbose_name='コメント'
        )
    # イメージのフィールド1
    image1 = models.ImageField(
        verbose_name='イメージ1',
        upload_to= 'photos'
        )
    # イメージのフィールド2
    image2 = models.ImageField(
        verbose_name='イメージ2',
        upload_to= 'photos',
        blank=True,
        null=True
        )
    # 投稿日時のフィールド
    posted_at = models.DateTimeField(
        verbose_name='投稿日時',
        auto_now_add=True
        )
    
    def __str__(self):
        '''オブジェクトを文字列に変換して返す
        
        Return(str):投稿記事のタイトル
        '''
        return self.title

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    '''ModelFormのサブクラス
    '''
    class Meta:
        '''ModelFormのインナークラス
        
        Attributes:
            model:モデルのクラス
            fields:フォームで使用するモデルのフィールドを設定
        '''
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

photo/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
# django.views.genericからTemplateView、ListViewをインポート
from django.views.generic import TemplateView, ListView
# django.views.genericからCreateViewをインポート
from django.views.generic import CreateView
# django.urlsからreverse_lazyをインポート
from django.urls import reverse_lazy
# formsモジュールからPhotoPostFormをインポート
from .forms import PhotoPostForm
# method_decoratorをインポート
from django.utils.decorators import method_decorator
# login_requiredをインポート
from django.contrib.auth.decorators import login_required
# modelsモジュールからPhotoPostをインポート
from .models import PhotoPost
# django.views.genericからDetailViewをインポート
from django.views.generic import DetailView
# django.views.genericからDeleteViewをインポート
from django.views.generic import DeleteView

class IndexView(ListView):
    '''トップページのビュー
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # モデルBlogPostのオブジェクトにorder_by()を適用して
    # 投稿日時の降順で並べ替える
    queryset = PhotoPost.objects.order_by('-posted_at')
    # 1ページに表示するレコードの件数
    paginate_by = 9

# デコレーターにより、CreatePhotoViewへのアクセスはログインユーザーに限定される
# ログイン状態でなければsettings.pyのLOGIN_URLにリダイレクトされる
@method_decorator(login_required, name = 'dispatch')
class CreatePhotoView(CreateView):
    '''写真投稿ページのビュー
    
    PhotoPostFormで定義されているモデルとフィールドと連携して
    投稿データをデータベースに登録する
    
    Attributes:
        form_class:モデルとフィールドが登録されたフォームクラス
        template_name:レンダリングするテンプレート
        success_url:データベースへの登録完了後のリダイレクト先
    '''
    # forms.pyのPhotoPostFormをフォームクラスとして登録
    form_class = PhotoPostForm
    # レンダリングするテンプレート
    template_name = "post_photo.html"
    # フォームデータ登録完了後のリダイレクト先
    success_url = reverse_lazy('photo:post_done')
    
    def form_valid(self, form):
        '''CreateViewクラスのform_valid()をオーバーライド
        
        フォームのバリデーションを通過したときに呼ばれる
        フォームデータの登録をここで行う
        
        parameters:
            form(django.forms.Form):
                form_classに格納されているPhotoPostFormオブジェクト
        Return:
            HttpRespomseRedirectオブジェクト:
            success_urlでせっていされているURLにリダイレクトさせる
        '''
        # commit = FalseにしてPOSTされたデータを取得
        postdata = form.save(commit=False)
        # 
        postdata.user = self.request.user
        # 
        postdata.save()
        # 
        return super().form_valid(form)
    
class PostSuccessView(TemplateView):
    '''登録完了ページのビュー
    
    Attributes:
        temolate_name:レンダリングするテンプレート
    '''
    # index.htmlをレンダリングする
    template_name = 'post_success.html'
    
class CategoryView(ListView):
    '''カテゴリページのビュー
    
    Attributes:
        template_name:レンダリングするテンプレート
        paginate_by:1ページに表示するレコードの件数
    '''
    # index.htmlをレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9
    
    def get_queryset(self):
        '''クエリを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく、
        get_queryset()のオーバーライドによりクエリを実行する
        
        Returns:
            queryによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し
        # categoryキーの値(Categorytableのid)をを取得
        category_id = self.kwargs['category']
        # filter(フィールド名 = id)で絞り込む
        categories = PhotoPost.objects.filter(
            category = category_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return categories
    
class UserView(ListView):
    '''ユーザーの投稿一覧ページのビュー
    Attributes:
        template_name:レンダリングするテンプレート
        paginate_by:1ページに表示するレコードの件数
    '''
    # index.htmlにレンダリングする
    template_name = 'index.html'
    # 1ページに表示するレコードの件数
    paginate_by = 9
    
    def get_queryset(self):
        '''クエルを実行する
        self.kwargsの取得が必要なため、クラス変数querysetではなく
        get_queryset()ノオーバーライドによりクエリを実行する
        
        Returns:クエリによって取得されたレコード
        '''
        # self.kwargsでキーワードの辞書を取得し、
        # userキーの値(ユーザーテーブルのid)を取得
        user_id = self.kwargs['user']
        # filter(フィールド名=id)で絞り込む
        user_list = PhotoPost.objects.filter(
            user = user_id).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return user_list
    
class DetailView(DetailView):
    '''詳細ページのビュー
    
    投稿記事の詳細を表示するのでDetailViewを継承する
    Attributes:
        template_name:レンダリングするテンプレート
        model:モデルのクラス
    '''
    # post.htmlをレンダリングする
    template_name = 'detail.html'
    # クラス変数modelにモデルBlogPostを設定
    model = PhotoPost
    
class MypageView(ListView):
    '''マイページのビュー
    
    Attributes:
        template_name:レンダリングするテンプレート
        paginate_by:1ページに表示するレコードの件数
    '''
    # mypage.html
    template_name = 'mypage.html'
    
    paginate_by = 9
    
    def get_queryset(self):
        '''クエルを実行する
        
        self.kwargsの取得が必要なため、クラス変数querysetではなく
        get_queryset()ノオーバーライドによりクエリを実行する
        
        Returns:クエリによって取得されたレコード
        '''
        # 現在ログインしているユーザー名はHttpRequest.userに格納されている
        # filter(userフィールド=userオブジェクト)で絞り込む
        queryset = PhotoPost.objects.filter(
            user = self.request.user).order_by('-posted_at')
        # クエリによって取得されたレコードを返す
        return queryset
    
class PhotoDeleteView(DeleteView):
    '''レコードの削除行うビュー
    
    Attributes:
        model:モデル
        template_name:レンダリングするテンプレート
        paginate_by:1ページに表示するレコードの件数
        success_url:削除完了後のリダイレクト先のURL
    '''
    # 操作の対象はPhotoPostモデル
    model = PhotoPost
    # photo_delete.htmlをレンダリングする
    template_name = 'photo_delete.html'
    # 処理完了後にマイページにリダイレクト
    success_url = reverse_lazy('photo:mypage')
    
    def delete(self, request, *args, **kwargs):
        '''レコードの削除を行う
        
        Parameters:
            self:PhotoDeleteViewオブジェクト
            request:WSGIRewuest(HttpRequest)オブジェクト
            args:引数として渡される辞書(dict)
            kwargs:キーワード付きの辞書(dict)
            {'pk':21}
            
        Returns:
            HttpResponseRedirect(success_url)を返して
            success_urlにリダイレクト
        '''
        # スーパークラスのdelete()を実行
        return super().delete(request, *args, **kwargs)

photo/templates/base.html
<!-- 静的ファイルのURLを生成するstaticタグをダウンロードする -->
{% load static %}
<!doctype html>
<!-- 言語指定をenからjaに変更 -->
<html lang="ja">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.112.5">
    <!-- ヘッダー情報のタイトルを個別に設定できるようにする -->
    <title>{% block title %}{% endblock %}</title>

    <!-- <link rel="canonical" href="https://"~>の記述を削除 -->    

    <!-- Bootstrap core CSS -->
    <!-- Bootstrap core CSSを読み込むコードをBootstrapからコピー-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style> 
  </head>
  
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
    <header data-bs-theme="dark">
      <!-- text-bg-darkのtextを削除 -->
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <!-- ヘッダーのタイトルと本文 -->
              <h4 class = "text-white">お気に入りを見つけよう！</h4>
              <p class="text-muted">
                誰でも参加できる写真投稿サイトです。
                自分で撮影した写真ならなんでもオッケー！
                でも、カテゴリに属する写真に限ります。
                コメントもつけてください！
              </p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4>Contact</h4>
              <ul class="list-unstyled">
                <!-- ナビゲーションメニュー -->
                {% if user.is_authenticated %}
                <!-- ログイン中のメニュー-->
                <li><a href="{% url 'photo:mypage' %}" class="text-white">マイページ</a></li>
                <li><a href="{% url 'accounts:logout' %}" class="text-white">ログアウト</a></li>
                <li><a href="{% url 'password_reset' %}" class="text-white">パスワードのリセット</a></li>
                <li><a href="mailto:admin@example.com"
                        class="text-white">Email me</a></li>
                {% else %}
                <!-- ログイン状態ではない場合のメニュー-->
                <li><a href="{% url 'accounts:signup' %}" class="text-white">サインアップ</a></li>
                <li><a href="{% url 'accounts:login' %}" class="text-white">ログイン</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
          <!-- トップページへのリンク -->
          <a href="{% url 'photo:index' %}"
              class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
            <!-- リンクテキスト -->
            <strong>Photo Gallery</strong>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main>
      <!-- <main>タグの要素をすべて削除し低下に書き換え -->
      <!-- メインコンテンツの本体部分は各ページのテンプレートで埋め込む -->
      {% block contents %}{% endblock %}
    </main>

    <footer class="text-body-secondary py-5">
      <div class="container">
        <p class="float-end mb-1">
          <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Gallery is &copy; Bootstrap, but please post a lot!</p>
        <!-- <p class="mb-0">は末尾の</p>まで削除 -->
      </div>
    </footer>

    <!-- BootstrapからJavaScriptを読み込むコードをコピーして貼り付け -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
                crossorigin="anonymous"></script>
  </body>
</html>

photo/templates/photos_title.html
<!-- ここまでのコードをすべて削除 -->

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <!-- タイトルと本文 -->
        <h1 class="fw-light">Photo Gallery</h1>
        <p class="lead text-body-secondary">
          コメントを見て写真に描かれた世界に思いを馳せましょう。
          素敵な写真とコメントをお待ちしています！
        </p>
        <p>
          <!-- ナビゲーションボタン -->
          {% if user.is_authenticated %}
          <!-- ログイン中のボタン -->
          <a href="{% url 'photo:post' %}"
              class="btn btn-primary my-2">投稿する</a>
          <a href="{% url 'accounts:logout' %}"
              class="btn btn-secondary my-2">ログアウト</a>
          {% else %}
          <!-- ログイン状態ではない場合のボタン -->
          <a href="{% url 'accounts:signup' %}"
              class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}"
              class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>

<!-- 以下のコードをすべて削除 -->